version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo prebuild start
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/awsPipelineDemo-0.0.1-SNAPSHOT.jar
  name:
    - awsPipelineDemo.jar